### ISSUE TITLE
IDA Freeware Link directs to V7 (which is not able to disassemble DOS exes)

### ISSUE THREAD

**Issue by LowLevelMahn** [xor2003/masm2c#1]
the current IDA freeware 7 on https://www.hex-rays.com/products/ida/support/download_freeware.shtml
is not able to disassemble dos executables

But the ScummVM project got the approval of hex-rays to distrubute the old version 5 that is still able to disassembler dos exes
https://www.scummvm.org/news/20180331/

**Comment by xor2003** [comment]
Thanks
