### ISSUE TITLE
using old linker?

### ISSUE THREAD

**Issue by LowLevelMahn** [xor2003/masm2c#2]
i saw you using the old alink.exe

a good and very up to date Linker that is still 16bit able is UniLink:
ftp://ftp.styx.cabel.net/pub/UniLink
(im linking QuickC 2 obj files with that on)

or WLink from the Watcom V2 project

or Optlink from DMC or DMD package

**Comment by xor2003** [comment]
Thanks. I also found usefull examples of different tools in the UASM distribution at \Samples\Dos\

**Comment by xor2003** [comment]
Do you have some contacts so the could chat?

**Comment by LowLevelMahn** [comment]
meet me on efnet.org/irc, #masm2c :)

**Comment by xor2003** [comment]
Thanks. it is a good tool. I was able to build BC++ 5 target with it.
