### ISSUE TITLE
MASM format

### ISSUE THREAD

**Issue by Skin36** [xor2003/masm2c#4]
how to get the MASM format from the IDA?

**Comment by xor2003** [comment]
Looks like by default it generates almost MASM format.
Options->Analysis->Target Assembler->Generic for Intel 80x86

**Comment by Skin36** [comment]
the script masm2c.py generates an error for the same names of different structures. Is it correct ?

**Comment by LowLevelMahn** [comment]
-what are you reversing? System/Exe-Type etc.
-did it assembles with Masm (IDAs output is normaly not out-of-the-box buildable - depending of what are you reversing (16bit, DOS, Windows, Binary...)
-sample?

**Comment by xor2003** [comment]
Also structure support is under development. See TODO

**Comment by Skin36** [comment]
![изображение](https://user-images.githubusercontent.com/9459863/108214205-f4923400-7140-11eb-95dc-5e11554708c3.png)

**Comment by Skin36** [comment]
But this is not a global name, I am just the name of a member of the structure

**Comment by xor2003** [comment]
Sctructures and macro support is the current next step

**Comment by xor2003** [comment]
You didn't provided enought information.
I prepared workaround: [commit](https://github.com/xor2003/masm2c/commit/2fb4d7f8934087bdf35889f8caf9a5ec944b636a)
Try latest version.
Structures are skipped.
