### ISSUE TITLE
command  "lahf" not supported

### ISSUE THREAD

**Issue by Skin36** [xor2003/masm2c#5]
command  "lahf" not supported

-32 bit DOS
-Protected
-IDA

![изображение](https://user-images.githubusercontent.com/9459863/108262151-96337880-7175-11eb-9cbb-f795dbf84125.png)

**Comment by xor2003** [comment]
I fixed it.
For 32 bit it make sense to use IDA Decompiler instead

**Comment by xor2003** [comment]
Not sure 32 bit protected target still works for masm2c. Will need to found time to test

**Comment by LowLevelMahn** [comment]
i think he needs to strip off to extender stuff somewhat - switching to protected mode isn't implemented in your adapation layer, or?

**Comment by xor2003** [comment]
I think dos protected mode target was working with DJGPP previously. It is using extender.
(I think he reversing APOC game) Most of software using extenders for DOS 32 protected.

**Comment by xor2003** [comment]
@Skin36 are you from Russia as me?

**Comment by Skin36** [comment]
yes

**Comment by Skin36** [comment]
command sahf not supoport too

**Comment by LowLevelMahn** [comment]
> I fixed it.
> For 32 bit it make sense to use IDA Decompiler instead

or reverse it like the Syndicate Port was done - because it is already 32 bit

https://gynvael.coldwind.pl/?id=279
http://swars.vexillium.org/

**Comment by xor2003** [comment]
Did you tryied latest masm2c? LAHF, SAHF works for me.

**Comment by Skin36** [comment]
ah sorry need to update

**Comment by Skin36** [comment]
wtat about FPU support ?

**Comment by xor2003** [comment]
I see it to complex for now for me.
I found some 387 instructions emulator in the old linux kernel.
It can be used as a start.
So not very soon

**Comment by xor2003** [comment]
Any way you can translate part without FPU.

**Comment by Skin36** [comment]
Почему нельзя просто добавить команды FPU,  как и остальные команды ?

**Comment by xor2003** [comment]
Остальные команды эмулируются с помощью C. Посмотри asm.h
1. Эмуляцию задолбишься реализовывать. 
2. Мне надо разобраться вообще как FPU инструкции работают.
Там 387 как-то стек использует.
Сейчас наверно можно вместо реальной реализации сделать asm вставки.
3. Может где есть готовая? Наверно можно выдрать из DOSBOX fpu_instructions.h

32 protected - зачем вообще тебе моя программа? там сегментация не используется.
IDA декомпилятор генерит чистые C функции. Для 32бит нет проблемы такой сильной проблемы соотнести константу в дизассемблере и переменную, как для 16 бит где сегментация.
Кроме IDA есть еще куча декомпиляторов в С типа retdec, snowman. Вроде мне IDA больше понравился.

Мои проекты по реверсингу почти все 16битные.

**Comment by Skin36** [comment]
asm вставки, да самое то. А что толку с Декомпилятора иды ? Все что мог я уже получил. А мне нужен динамический анализ. Если функция большая , да еще с FPU командами(логарифмы и прочее) то как она работает разобраться нельзя. Только запустить ее, откомпилировав. Пока  на небольших функциях я делю на Фасме. Но хотелось бы что то универсальное.

**Comment by xor2003** [comment]
В dosbox debuger есть LOGCPU там можно поглядеть что происходит в регистрах и памяти

**Comment by Skin36** [comment]
как думаешь можно сделать скрипт чтобы именно в Си инструкции переводить ? Насколько это сложно ? Вот я смотрю , компилятор использует одни и те же алгоритмы, и даже без декомпиляции можно понять что происходит. Хотя бы для конкретного компилятора.

**Comment by xor2003** [comment]
https://www.hex-rays.com/products/decompiler/compare/compare_vs_disassembly/
https://retdec.com/
https://ai.facebook.com/blog/deep-learning-to-translate-between-programming-languages/

**Comment by xor2003** [comment]
Декомпилятор от дизассемблера отличаешь?

**Comment by Skin36** [comment]
да, конечно

**Comment by LowLevelMahn** [comment]
Ghidra (https://ghidra-sre.org/) is free and also supports Decompilation (even 16bit) - nowhere near as good as the IDA Hex-Rays Decompiler but still helpfull

**Comment by Skin36** [comment]
rdtsc command  not supported
