### ISSUE TITLE
Convert multiple .asm files with data segments distributed across files

### ISSUE THREAD

**Issue by LowLevelMahn** [xor2003/masm2c#7]
last time we talked you just started the real MASM parser based on the grammar

still fighting?

**Comment by xor2003** [comment]
This one is mostly finished. 
And it is already great move forward.
I think the whole source code can be parsed now.
Tool produces C++ code.
I was adding/fixing structures support and converting many ASM -> C++ files so they can be compiled together.
Also need to properly test structures support and make it all compile.
Busy with personal life currently.

**Comment by LowLevelMahn** [comment]
> This one is mostly finished.
> And it is already great move forward.

sounds great, thanks for all the hard work so far

> Also need to properly test structures support and make it all compile.

i hope i can help with testing or getting it finished
also the stunts community will be of great help if you reach someday the state of testing the results

> Busy with personal life currently.

we all :)

**Comment by xor2003** [comment]
Ok I will make sure you can start to use it.

**Comment by xor2003** [comment]
Current issue with restunts: when converting several .asm files the masm behaviour is to merge several segement which are part of segment group into single data segment. Or just to have data segment in different files.
The current masm2c implementation was: data is a single structure without gaps. (all the segments). Previously it was designed to convert single file.
The solutions I see:
1. Make some preprocessing. Separate cpp file with data will include all data from all data segments. Masm2c will mimic masm behaviour. Complex to implement. I already implemented a lot of complexities...
2. Merge all the files and produce single cpp.

What is your view?

**Comment by xor2003** [comment]
I mean you probably can convert each file. 
And it should be enough to convert separate functions.
Just to need to manual merge to compile togheher.

**Comment by LowLevelMahn** [comment]
i hope i can to do some testing on the weekend - currently very busy

a complete-all-files solution would be great - but i think its currently enough to get an idea how far one will come using your tool

**Comment by xor2003** [comment]
Finally it can compile 90% of restunts code!

**Comment by LowLevelMahn** [comment]
Great news, i think your converter will play a big role in reversing of 16bit code games in the future

**Comment by xor2003** [comment]
Merging data segments implemented. Case closed
